// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Blob is an autogenerated mock type for the Blob type
type Blob struct {
	mock.Mock
}

// Reader provides a mock function with given fields:
func (_m *Blob) Reader() (io.ReadCloser, error) {
	ret := _m.Called()

	var r0 io.ReadCloser
	if rf, ok := ret.Get(0).(func() io.ReadCloser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBlob interface {
	mock.TestingT
	Cleanup(func())
}

// NewBlob creates a new instance of Blob. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBlob(t mockConstructorTestingTNewBlob) *Blob {
	mock := &Blob{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
