// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	backend "github.com/GlintPay/gccs/backend"
	mock "github.com/stretchr/testify/mock"
)

// discoveryHandler is an autogenerated mock type for the discoveryHandler type
type discoveryHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: f
func (_m *discoveryHandler) Execute(f backend.File) error {
	ret := _m.Called(f)

	var r0 error
	if rf, ok := ret.Get(0).(func(backend.File) error); ok {
		r0 = rf(f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewDiscoveryHandler interface {
	mock.TestingT
	Cleanup(func())
}

// newDiscoveryHandler creates a new instance of discoveryHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newDiscoveryHandler(t mockConstructorTestingTnewDiscoveryHandler) *discoveryHandler {
	mock := &discoveryHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
